#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.demo.entity
  mapperLocations: classpath:mapping/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/manage?serverTimezone=UTC
    username: root
    password: wlzl0119
    driver-class-name: com.mysql.cj.jdbc.Driver

#输出日志
logging:
  path: D:/data/myLog
  file: myLog.log
  level:
    com.demo: debug
    root: INFO
